// MIT — ported from elkowar/eww crates/notifier_host/src/proxy/dbus_status_notifier_item.rs
//! DBus proxy for `org.kde.StatusNotifierItem`.
//! Generated by `zbus-xmlgen` 3.1.0 from the Waybar protocol XML.

#![allow(clippy::type_complexity)]

use zbus::dbus_proxy;

#[dbus_proxy(interface = "org.kde.StatusNotifierItem", assume_defaults = true)]
trait StatusNotifierItem {
    fn activate(&self, x: i32, y: i32) -> zbus::Result<()>;
    fn context_menu(&self, x: i32, y: i32) -> zbus::Result<()>;
    fn scroll(&self, delta: i32, orientation: &str) -> zbus::Result<()>;
    fn secondary_activate(&self, x: i32, y: i32) -> zbus::Result<()>;

    #[dbus_proxy(signal)]
    fn new_attention_icon(&self) -> zbus::Result<()>;
    #[dbus_proxy(signal)]
    fn new_icon(&self) -> zbus::Result<()>;
    #[dbus_proxy(signal)]
    fn new_overlay_icon(&self) -> zbus::Result<()>;
    #[dbus_proxy(signal)]
    fn new_status(&self, status: &str) -> zbus::Result<()>;
    #[dbus_proxy(signal)]
    fn new_title(&self) -> zbus::Result<()>;
    #[dbus_proxy(signal)]
    fn new_tool_tip(&self) -> zbus::Result<()>;

    #[dbus_proxy(property)]
    fn attention_icon_name(&self) -> zbus::Result<String>;
    #[dbus_proxy(property)]
    fn attention_icon_pixmap(&self) -> zbus::Result<Vec<(i32, i32, Vec<u8>)>>;
    #[dbus_proxy(property)]
    fn attention_movie_name(&self) -> zbus::Result<String>;
    #[dbus_proxy(property)]
    fn category(&self) -> zbus::Result<String>;
    #[dbus_proxy(property(emits_changed_signal = "false"))]
    fn icon_name(&self) -> zbus::Result<String>;
    #[dbus_proxy(property(emits_changed_signal = "false"))]
    fn icon_pixmap(&self) -> zbus::Result<Vec<(i32, i32, Vec<u8>)>>;
    #[dbus_proxy(property)]
    fn icon_theme_path(&self) -> zbus::Result<String>;
    #[dbus_proxy(property)]
    fn id(&self) -> zbus::Result<String>;
    #[dbus_proxy(property)]
    fn item_is_menu(&self) -> zbus::Result<bool>;
    #[dbus_proxy(property)]
    fn menu(&self) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;
    #[dbus_proxy(property)]
    fn overlay_icon_name(&self) -> zbus::Result<String>;
    #[dbus_proxy(property)]
    fn overlay_icon_pixmap(&self) -> zbus::Result<Vec<(i32, i32, Vec<u8>)>>;
    #[dbus_proxy(property)]
    fn status(&self) -> zbus::Result<String>;
    #[dbus_proxy(property)]
    fn title(&self) -> zbus::Result<String>;
    #[dbus_proxy(property)]
    fn tool_tip(&self) -> zbus::Result<(String, Vec<(i32, i32, Vec<u8>)>)>;
}
