// MIT — ported from elkowar/eww crates/notifier_host/src/proxy/dbus_status_notifier_watcher.rs
//! DBus proxy for `org.kde.StatusNotifierWatcher`.
//! Generated by `zbus-xmlgen` 3.1.0, adjusted with default service/path.

use zbus::dbus_proxy;

#[dbus_proxy(
    default_service = "org.kde.StatusNotifierWatcher",
    interface = "org.kde.StatusNotifierWatcher",
    default_path = "/StatusNotifierWatcher"
)]
trait StatusNotifierWatcher {
    fn register_status_notifier_host(&self, service: &str) -> zbus::Result<()>;
    fn register_status_notifier_item(&self, service: &str) -> zbus::Result<()>;

    #[dbus_proxy(signal)]
    fn status_notifier_host_registered(&self) -> zbus::Result<()>;
    #[dbus_proxy(signal)]
    fn status_notifier_host_unregistered(&self) -> zbus::Result<()>;
    #[dbus_proxy(signal)]
    fn status_notifier_item_registered(&self, service: &str) -> zbus::Result<()>;
    #[dbus_proxy(signal)]
    fn status_notifier_item_unregistered(&self, service: &str) -> zbus::Result<()>;

    #[dbus_proxy(property)]
    fn is_status_notifier_host_registered(&self) -> zbus::Result<bool>;
    #[dbus_proxy(property)]
    fn protocol_version(&self) -> zbus::Result<i32>;
    #[dbus_proxy(property)]
    fn registered_status_notifier_items(&self) -> zbus::Result<Vec<String>>;
}
