// MIT — ported from elkowar/eww crates/notifier_host/src/proxy/mod.rs
//! Proxies for DBus services.
//!
//! Generated by `zbus-xmlgen` from the Waybar protocol XML files, then
//! lightly adjusted (watcher default service/path annotations).

mod dbus_status_notifier_item;
pub use dbus_status_notifier_item::*;

mod dbus_status_notifier_watcher;
pub use dbus_status_notifier_watcher::*;
